[package]
name = "solana-message"
description = "Solana transaction message types."
documentation = "https://docs.rs/solana-message"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["traits-preview"] }
lazy_static = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-bincode = { workspace = true, optional = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-nonce = { workspace = true }
solana-pubkey = { workspace = true }
solana-sanitize = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-short-vec = { workspace = true, optional = true }
solana-system-interface = { git = "https://github.com/solana-program/system.git", optional = true }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
solana-message = { path = ".", features = ["dev-context-only-utils"] }
solana-program = { path = "../program" }
solana-sha256-hasher = { workspace = true }

[features]
bincode = [
    "dep:bincode",
    "dep:solana-bincode",
    "dep:solana-system-interface",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:solana-short-vec",
    "solana-hash/serde",
    "solana-pubkey/serde",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
