[package]
name = "solana-message"
description = "Solana transaction message types."
documentation = "https://docs.rs/solana-message"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
blake3 = { workspace = true, features = ["traits-preview"] }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
solana-bincode = { workspace = true }
solana-hash = { workspace = true, features = ["serde"] }
solana-instruction = { workspace = true, features = ["std"] }
solana-nonce = { workspace = true }
solana-pubkey = { workspace = true, features = ["serde"] }
solana-sanitize = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-short-vec = { workspace = true }
solana-system-interface = { git = "https://github.com/solana-program/system.git" }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
solana-program = { path = "../program" }
solana-sha256-hasher = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
