[package]
name = "solana-hasher"
description = "Solana SHA256 hashing"
documentation = "https://docs.rs/solana-hasher"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-hash = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
sha2 = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
sha2 = { workspace = true, optional = true }
solana-define-syscall = { workspace = true }

[features]
sha2 = ["dep:sha2"]

[dev-dependencies]
bs58 = { workspace = true }
