[package]
name = "solana-program-error"
description = "Solana Program Error"
documentation = "https://docs.rs/solana-program-error"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true, optional = true }
num-traits = { workspace = true }
solana-decode-error = { workspace = true }
solana-msg = { workspace = true }

[features]
borsh = ["dep:borsh"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
