[package]
name = "solana-program-lite-split"
description = "Solana Program"
documentation = "https://docs.rs/solana-program"
readme = "README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.75.0"                          # solana platform-tools rust version

[dependencies]
solana-account-info = { workspace = true }
solana-decode-error = { workspace = true }
solana-debug-account-data = { workspace = true }
solana-entrypoint = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-log = { workspace = true }
solana-program-error = { workspace = true }
solana-program-memory = { workspace = true }
solana-pubkey = { workspace = true }
solana-sanitize = { workspace = true }
solana-sdk-macro = { workspace = true }
solana-syscalls = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["borsh"]
borsh = [
    "solana-hash/borsh",
    "solana-instruction/borsh",
    "solana-program-error/borsh",
    "solana-pubkey/borsh",
]
frozen-abi = [
    "solana-hash/frozen-abi",
    "solana-instruction/frozen-abi",
    "solana-pubkey/frozen-abi",
]
