[package]
name = "solana-program-error"
description = "Solana Program"
documentation = "https://docs.rs/solana-program"
readme = "README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.75.0"                          # solana platform-tools rust version

[dependencies]
borsh = { workspace = true, optional = true }
num-traits = { workspace = true, features = ["i128"] }
serde = { workspace = true }
serde_derive = { workspace = true }
solana-decode-error = { workspace = true }
solana-instruction = { workspace = true }
solana-msg = { workspace = true }
solana-pubkey = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["borsh"]
borsh = ["dep:borsh"]
